---
title: GreenVulcano Documentation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
images: /assets/images
logo: /assets/images/prova.png
permalink: pretty
owner_url: 
  url: http://www.greenvulcanotechnologies.com/
  
collections:
  my_collection:
    output: true

defaults:
 -
    scope:
      path: "{{site.baseurl}}"
    values:
      layout: "default"
  -
    scope:
      path: "pages"
    values:
      layout: "default_page"
 

